# Generated by Django 4.2 on 2024-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0003_rename_name_branch_branch_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='address',
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='address1',
            field=models.TextField(blank=True),
        ),
    ]
