# Generated by Django 4.2 on 2024-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0004_remove_deliverylocation_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverylocation',
            old_name='address1',
            new_name='delivery_location1',
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='delivery_location2',
            field=models.TextField(blank=True),
        ),
    ]
