# Generated by Django 4.2 on 2024-07-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0005_rename_address1_deliverylocation_delivery_location1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
