# Generated by Django 4.2 on 2024-07-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0006_companyinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
