# Generated by Django 4.2 on 2024-07-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0007_companyinfo_company_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_manager',
            new_name='branch_name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='delivery_locations',
        ),
        migrations.AddField(
            model_name='branch',
            name='company_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
