# Generated by Django 4.2 on 2024-07-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0008_rename_branch_manager_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
