# Generated by Django 4.2 on 2024-07-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminDashboard', '0013_corporatemealplan_corporate_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporatemealplan',
            old_name='corporate_cuisine_choices',
            new_name='cuisine_choices',
        ),
        migrations.RenameField(
            model_name='corporatemealplan',
            old_name='corporate_dietary_choices',
            new_name='dietary_choices',
        ),
    ]
